apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  username: {{ .Values.smsUsername }}
  password: {{ .Values.smsPassword }}
  calendar_ics_url: {{ .Values.calendarIcsUrl }}
