environmentKinds:
  - onprem
  - tenant
  - legacy
  - management
values:
  image.tag:
    displayName: Image tag
    config:
      type: string
  smsPassword:
    displayName: SMS-service password
    required: true
    config:
      type: string
      secret: true
  smsUsername:
    displayName: SMS-service username
    required: true
    config:
      type: string
  smsHost:
    displayName: SMS-service domain
    config:
      type: string
  platformPartnerId:
    displayName: LinkMobility partner ID
    required: true
    config:
      type: string
  calendarIcsUrl:
    displayName: Google Calendar ICS URL (private)
    required: true
    config:
      type: string
      secret: true
  extraEnv.HTTPS_PROXY:
    displayName: HTTPS proxy
    config:
      type: string
    ignoreKind:
      - tenant
  extraEnv.NO_PROXY:
    displayName: NO_PROXY
    config:
      type: string
    ignoreKind:
      - tenant
  extraEnv.TENANT:
    computed:
      template: '"{{ .Tenant.Name }}"'
